### ISSUE TITLE
Warning about deprecated `set-output` command

### ISSUE THREAD

**Issue by alexciesielski** [joerick/pr-labels-action#9]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by joerick** [comment]
prs welcome!

**Comment by alexciesielski** [comment]
Happy to hear, was worried that the repo has become inactive :)
I took a look at the git client and it seems that they have deprecated the command without giving an alternative lol:

https://github.com/actions/toolkit/issues/1218

I'm subscribed to this - once they push an update to the client I'll open a PR here.

Cheers

**Comment by educorzo** [comment]
Hi @joerick,
Any plan for merging this PR and close this issue?

**Comment by kimlep01** [comment]
Hi, I updated my workflow to use `v1.0.8` and I'm still seeing the same warnings

My repo:
```
Run joerick/pr-labels-action@v1.0.8

Found label  do-not-merge 
  Setting env var for remaining steps: GITHUB_PR_LABEL_DO_NOT_MERGE=1

Action output:
labels: " do-not-merge "
labels-object: {"do-not-merge":true}
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Latest PR check in this repo https://github.com/joerick/pr-labels-action/actions/runs/4469843040/jobs/7852529676: 
```
Run ./
Not a pull request
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[2](https://github.com/joerick/pr-labels-action/actions/runs/4469843040/jobs/7852529676#step:3:3)022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Could you verify and reopen this ticket? This will start failing on June 1st.

**Comment by alexciesielski** [comment]
Looks like the `dist` folder has not been updated? I still see the `set-output` command here: https://github.com/joerick/pr-labels-action/blob/main/dist/index.js#L333
